name: Common Test Steps
description: Shared steps to install and test gr_libs
runs:
  using: "composite"
  steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    # - name: Copy dataset into working directory
    #   run: |
    #     mkdir -p "${{ github.workspace }}/dataset"
    #     cp -r /preloaded_data/* "${{ github.workspace }}/dataset/"
      # shell: bash

    - name: Show working dir and contents
      run: |
        pwd
        tree -L 3 || true
      shell: bash

    - name: Install gr_libs with all extras and test tools
      env:
        SETUPTOOLS_SCM_PRETEND_VERSION_FOR_GR_LIBS: "0.0.0"
      run: |
        python -m pip install --upgrade pip
        pip install setuptools_scm
        pip install gr_envs[minigrid,panda,highway,maze]
        pip install .[minigrid,panda,highway,maze]
        pip install pytest
      shell: bash

    - name: Run tests
      run: pytest tests -v -s
      shell: bash
