name: Common Test Steps

on:
  workflow_call:

jobs:
  test_steps:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/matanshamir1/gr_test_base_slim:latest
      options: --user root
    steps:
      - name: Show working dir and contents
        run: |
          pwd
          ls -R

      - name: Install gr_libs with all extras and test tools
        env:
          SETUPTOOLS_SCM_PRETEND_VERSION_FOR_GR_LIBS: "0.0.0"
        run: |
          python -m pip install --upgrade pip
          pip install setuptools_scm
          pip install gr_envs[minigrid,panda,highway,maze]
          pip install .[minigrid,panda,highway,maze]
          pip install pytest

      - name: Run tests
        run: pytest tests/
