name: PR Test Flow

on:
  pull_request:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/matanshamir1/gr_test_base_slim:latest
      options: --user root
    steps:
      - name: Run common test steps
        uses: ./.github/actions/common-test-steps
