name: PR Test Flow

on:
  pull_request:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/matanshamir1/gr_test_base:latest
      options: --user root
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Free up disk space
        run: |
          echo "Before cleanup:"
          df -h

          rm -rf /usr/share/dotnet || true
          rm -rf /usr/local/lib/android || true
          rm -rf /opt/ghc || true
          apt-get clean || true
          rm -rf ~/.cache/pip || true

          echo "After cleanup:"
          df -h
        shell: bash

      - name: Run common test steps
        uses: ./.github/actions/common-test-steps
