name: Publish to PyPI

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/matanshamir1/gr_image:latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # fetch full git history so setuptools_scm can find the tag


      - name: Run common test steps
        uses: ./.github/actions/common-test-steps

      - name: Install build tools
        run: pip install build twine

      - name: Build the package
        run: python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: python -m twine upload dist/*
